meta:
  default:
    azs: [z1, z2, z3]
  domain: (( grab params.vault_domain || "vault.bosh" ))

exodus:
  ips: (( grab instance_groups.vault.networks[0].static_ips ))

instance_groups:
- name: vault
  jobs:
  - name: vault
    release: safe
    properties:
      safe:
        ui: (( grab params.ui || true ))
        peer:
          tls:
            certificate: (( vault meta.vault "/certs/consul:certificate" ))
            key:         (( vault meta.vault "/certs/consul:key" ))
            ca:          (( vault meta.vault "/certs/ca:certificate" ))
        tls:
          certificate: (( vault meta.vault "/certs/vault:certificate" ))
          key:         (( vault meta.vault "/certs/vault:key" ))

  instances: 3
  azs:       (( grab params.availability_zones || meta.default.azs ))

  persistent_disk_type: (( grab params.vault_disk_pool || "default" ))
  vm_type:              (( grab params.vault_vm_type   || "default" ))

  stemcell: default
  networks:
  - name:       (( grab params.vault_network || "vault" ))
    static_ips: (( static_ips(0, 1, 2) ))

update:
  serial: true
  canaries: 1
  canary_watch_time: 30000-120000
  max_in_flight: 1
  update_watch_time: 30000-120000

releases:
  - name:    safe
    version: 0.3.0
    url:     https://github.com/cloudfoundry-community/safe-boshrelease/releases/download/v0.3.0/safe-0.3.0.tgz
    sha1:    ee009da0398ec1688ccfe830d68957be49571b0a

stemcells:
  - alias:   default
    os:      (( grab params.stemcell_os      || "ubuntu-xenial" ))
    version: (( grab params.stemcell_version || "latest"        ))
